---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Checking if nginx is listening on port 80
    uri:
      url: http://localhost
      status_code: 200
