---
- hosts: all
  become: true
  vars:
    shiny_version: 1.5.18.987
    ssl_path: /etc/http/ssl/
    ssl_csr: /etc/http/ssl/acme.csr
    ssl_private_key: /etc/http/ssl/acme.pem
    ssl_public_cert: /etc/http/ssl/acme_public.pem
    ssl_fullchain: /etc/http/ssl/fullchain.crt
    ssl_inter_chain: /etc/http/ssl/intermediate.crt
  tasks:
    - name: Adding R repo's public key
      apt_key:
        url: https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc
        state: present

    - name: Adding R repo
      apt_repository:
        repo: deb https://cloud.r-project.org/bin/linux/ubuntu {{ ansible_distribution_release }}-cran40/
        state: present
        update_cache: true

    - name: Wait for any possibly running unattended upgrade to finish
      raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

    - name: Installing NGINX, Mariadb, and UFW
      apt:
        name:
        - nginx-core
        - ufw
        - r-base
        - gdebi-core
        state: present

    - name: Installing shiny R packages
      command: "R -e \"install.packages('shiny', repos='https://cran.rstudio.com/')\""

    - name: Installing rmarkdown R packages
      command: "R -e \"install.packages('rmarkdown', repos='https://cran.rstudio.com/')\""

    - name: Downloading shiny-server-{{ shiny_version }}
      get_url:
        url: "https://download3.rstudio.org/ubuntu-18.04/x86_64/shiny-server-{{ shiny_version }}-amd64.deb"
        dest: /opt/shiny-server-{{ shiny_version }}-amd64.deb

    - name: Installing shiny-server {{ shiny_version }}
      apt:
        deb: /opt/shiny-server-{{ shiny_version }}-amd64.deb
      register: 'apt_status'
      until: 'apt_status is success'
      delay: 10
      retries: 60

    - name: Making sure shiny-server is started and enabled on boot.
      service:
        name: shiny-server
        state: started
        enabled: true

    - name: Removing default nginx config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Copying shiny.conf into sites-available
      template:
        src: files/shiny.conf
        dest: /etc/nginx/sites-available/shiny
        mode: 0644

    - name: Enabling site
      file:
        src: /etc/nginx/sites-available/shiny
        dest: /etc/nginx/sites-enabled/shiny
        state: link
      notify: restart NGINX

    - name: Making sure nginx is started.
      service:
        name: nginx
        state: started
        enabled: true

    - name: Enabling UFW
      ufw:
        state: enabled

    - name: Rate limiting ssh
      ufw:
        rule: limit
        port: ssh
        proto: tcp

    - name: Allowing port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Allowing port 443
      ufw:
        rule: allow
        port: '443'
        proto: tcp

    - name: grabbing FQDN via curl
      uri:
        url: http://whatismyhostname.com/raw/hostname/
        return_content: true
      register: fqdn

    - name: Generating private key for ACME
      openssl_privatekey:
        path: "{{ ssl_private_key }}"

    - name: Generating CSR for ACME
      openssl_csr:
        path: "{{ ssl_csr }}"
        privatekey_path: "{{ ssl_private_key }}"

    - name: Creating a HTTP challenge
      acme_certificate:
        account_key_content: "{{ ssl_private_key }}"
        csr: "{{ ssl_csr }}"
        dest: "{{ ssl_public_cert }}"
      register: challenge

    - name: copying challenge data into file
      copy:
        dest: /var/www/html/{{ challenge['challenge_data'][{{ fqdn }}]['http-01']['resource'] }}
        content: "{{ challenge['challenge_data'][{{ fqdn }}]['http-01']['resource_value'] }}"
      when: challenge is changed and '"{{ fqdn }}"' in challenge['challenge_data']

    - name: Validating challenge and generating certificate
      acme_certificate:
        account_key_src: "{{ ssl_private_key }}"
        csr: "{{ ssl_csr }}"
        dest: "{{ ssl_public_cert }}"
        fullchain_dest: "{{ ssl_fullchain }}"
        chain_dest: "{{ ssl_inter_chain }}"
        data: "{{ challenge }}"

  handlers:
    - name: restart NGINX
      service:
        name: nginx
        state: restarted
    - name: restart shiny-server
      service:
        name: shiny-server
        state: restarted
