---
- hosts: all
  become: true
  vars:
    shiny_version: 1.5.18.987
  tasks:
    - name: Adding R repo
      apt_repo:
        repo: ppa:c2d4u.team/c2d4u4.0+
        state: present
        update: true

    - name: Installing NGINX, Mariadb, and UFW
      package:
        name:
        - nginx-core
        - ufw
        - r-base
        - gdebi-core
        state: present
    - name: Downloading shiny-server-{{ shiny_version }}
      get_url:
        url: "https://download3.rstudio.org/ubuntu-18.04/x86_64/shiny-server-{{ shiny_version }}-amd64.deb"
        dest: /home/ubuntu/
    - name: Installing shiny R packages
      command: R -e \"install.packages('shiny', repos='https://cran.rstudio.com/')\

    - name: Installing shiny-server {{ shiny_version }}
      command: gdebi shiny-server-{{ shiny_version }}-amd64.deb

    - name: Copying over into sites-available
      template:
        src: files/nginx-default-http.j2
        dest: /etc/nginx/sites-available/nginx-default
        mode: 0644

    - name: Generating Hello World!
      copy:
        src: hello_world.index
        dest: /var/www/html/index.html
        backup: yes
        mode: 0755
      notify: restart NGINX

    - name: Enabling site
      file:
        src: /etc/nginx/sites-available/nginx-default
        dest: /etc/nginx/sites-enabled/nginx-default
        state: link
      notify: restart NGINX

    - name: Making sure nginx is started.
      service:
        name: nginx
        state: started
        enabled: true

    - name: Enabling UFW
      ufw:
        state: enabled

    - name: Rate limiting ssh
      ufw:
        rule: limit
        port: ssh
        proto: tcp

    - name: Allowing port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Allowing port 443
      ufw:
        rule: allow
        port: '443'
        proto: tcp
  handlers:
    - name: restart NGINX
      service:
        name: nginx
        state: restarted
